version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    ports:
      - '5432:5432'
    volumes:
      - /.docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "deseases"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"


volumes:
  postgresql_data:
    driver: local
